#!/usr/bin/env node
/**
 * Propagates the deployed URLs from CloudFormation outputs into .env.local and
 * into GUIDE.md §A, so the guide's URL table can never go stale. Stale URLs in
 * a checklist cost ten minutes every single time.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ok, bad, dim, step } from "./env.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputsPath = path.join(root, "infra/cdk-outputs.json");

if (!existsSync(outputsPath)) {
  console.error(bad("infra/cdk-outputs.json missing — run `pnpm deploy:infra`."));
  process.exit(1);
}
const o = JSON.parse(readFileSync(outputsPath, "utf8")).GrowthxStack;

const urls = {
  GX_API_BASE: o.ApiBaseUrl,
  GX_CDN_URL: o.CdnUrl,
  GX_SITE_A_URL: o.SiteAUrl,
  GX_DASHBOARD_URL: o.DashboardUrl,
};

// .env.local — generated, gitignored, safe to delete and regenerate.
writeFileSync(
  path.join(root, ".env.local"),
  `# Generated by scripts/outputs.mjs — do not edit, do not commit.\n` +
    `# Regenerate with: pnpm deploy:infra  (or: pnpm exec node scripts/outputs.mjs)\n` +
    Object.entries(urls).map(([k, v]) => `${k}=${v}`).join("\n") + "\n"
);
console.log(step("Deployed URLs"));
for (const [k, v] of Object.entries(urls)) console.log(ok(`${k.padEnd(18)} ${v}`));

// GUIDE.md §A live-URL table
const guidePath = path.join(root, "GUIDE.md");
let guide = readFileSync(guidePath, "utf8");
const table =
  `| What | URL |\n|---|---|\n` +
  `| Site A (the "customer" page) | ${o.SiteAUrl} |\n` +
  `| Dashboard (Site B) | ${o.DashboardUrl} |\n` +
  `| API base | ${o.ApiBaseUrl} |\n` +
  `| CDN (\`g.js\`) | ${o.CdnUrl}/g.js |\n`;

const start = guide.indexOf("### Live URLs");
if (start !== -1) {
  const nextHeading = guide.indexOf("\n### ", start + 1);
  const end = nextHeading === -1 ? guide.length : nextHeading;
  guide =
    guide.slice(0, start) +
    `### Live URLs\n\n_Written automatically by \`scripts/outputs.mjs\` on every deploy._\n\n` +
    table +
    guide.slice(end);
  writeFileSync(guidePath, guide);
  console.log(ok("GUIDE.md §A updated"));
} else {
  console.log(dim("  (GUIDE.md §A 'Live URLs' heading not found — table not updated)"));
}
console.log();
